### ISSUE TITLE
Playlists and clips repeat endlessly

### ISSUE THREAD

**Issue by adrianwyard** [adrianwyard/jwplayer-enhancements#13]
Test case: https://counterbalance.org/testdir/test3.html This playlist has only one item, but it keeps repeating.

I'm not sure if this is a new issue or it was there all along. The param "repeat: 'false'" in cbfscripts.js should stop this, but perhaps it's not making it through to JW Player?

**Comment by adrianwyard** [comment]
https://developer.jwplayer.com/jwplayer/docs/jw8-player-configuration-reference

**Comment by kayecandy** [comment]
> I'm not sure if this is a new issue or it was there all along. The param "repeat: 'false'" in cbfscripts.js should stop this, but perhaps it's not making it through to JW Player?

Fixed this. Sorry this was an oversight on my part. This was due to the playlist not being referenced properly, and so the system doesn't detect whether or not it's the last item in the playlist.

```js
__onPlayerTime({position, offset}){
  . . .
  if(_pos > currPlaylist.end){
    // The bug was here
    // This if-block checks if current playlist item is the last
    // item in the playlist.
    //
    // `this.playlist.length` was returning undefined
    if(iPlaylist == this.playlist.length - 1){
      this.player.seek(currPlaylist.sources[0].starttime);
      this.player.stop();
    }else{
      this.player.next();
      this.player.trigger('seeked');
    }
  }
  . . .
}
```

The `stop` command is actually manually triggered by the _cndce-counterbalance.js_ script itself as you can see in the code above so `repeat:false` doesn't do anything in this context

**Comment by kayecandy** [comment]
Added `repeat` parameter to CBPlayer here 15a4416.

`repeat:true` and `repeat:false` would now work. If none was given, this defaults to `false`.
