### ISSUE TITLE
Going to 'Previous' clip loops.

### ISSUE THREAD

**Issue by adrianwyard** [adrianwyard/jwplayer-enhancements#7]
When on the second item and later: clicking before the start of the current item doesn't load it correctly, but seems to loop.

I initially thought this was a browser dependent issue as I saw it first in Firefox and Safari and Chrome worked correctly, but now Chrome seems to fail too.

**Comment by kayecandy** [comment]
The fixes from 82ec971 is a "band-aid" fix. It's not exactly how I wanted to address this issue, but I couldn't find any other available JWPlayer events that directly addresses the problem.

**The algorithm**
The initial algorithm is to use the `time` and `seek` events to check whether the current position is within bounds of the current playlist item and executes the prev/next accordingly.


**The bug**
The bug was caused by a conflict with next/prev playlist and the current player position. 

The `starttime` script sometimes gets executed _before_ the prev/next playlist event. So the player gets `seeked` to the desired `starttime` _first_, but then the prev/next playlist triggers another seek to either 0 seconds or where it was last played. This causes the playlist to loop.


**Band-aid solution**
I removed the listener for `seek` because for some reasons, it behaves differently on mp4 and hls formats. 

The ideal fix is to have a script _**stop**_ a seek action then and there, but I couldn't find any workaround on that. Something like `event.stopPropagation` would've solved this problem but JWPlayer currently has no functionality for it.

What this _band-aid_ solution does is basically wait for the player to seek to the user-selected time _first_ and then seek again to the desired _starttime_ of the playlist item. At the very least, the conflict stated above gets _solved (sort of)_

... but this causes a sort of _jump_ on the frames, so to fix that, I added cd5f5b2 to _block_ the prev/next sliders; that way, user-selected `seeks` doesn't get triggered to begin with.
